# SYNTHETIC TRAINING DATASET ------
training_data_path: "../training_data"
testing_data_path: "../detection_data"

# Simulated fish EOD
simulation_duration_rec: 240
samplerate: 20000
num_fish: [1, 10]
num_chirps: [10, 30]
num_rises: [0, 3]
noise_stds: [0, 0.001]
num_electrodes: 11
eodfs: [300, 1500]
chirp_sizes: [20, 150]
chirp_durations: [0.005, 0.1]
chirp_kurtoses: [0.6, 1.4]
chirp_contrasts: [0.0, 1.0]
rise_sizes: [10, 100]
rise_rise_taus: [0.1, 1.5]
rise_decay_taus: [2, 15]
frequency_track_samplerate: 3

# STFT spectrogram
frequency_resolution: 6  # df = fs / nfft
overlap_fraction: 0.99  # hanning window overlap
 
# Spectrogram ROI extraction
time_pad: 0.10
freq_pad: [-50, 200]
img_size_px: 128

# CNN MODEL ------
num_epochs: 10
batch_size: 10
learning_rate: 0.001
train_size: 0.8
save_dir: "models/model.pt"
plot_dir: "../assets"

# DETECTOR CONFIGURATION ------
detection_data_path: "../detection_data"
disk_cleanup: False
stride: 0.01
min_chirp_dt: 0.02
buffersize: 10
spectrogram_overlap: 1
num_electrodes: 11

# DATAGEN - TRAIN - TEST ------
# This value determines how often the
# routine
#   1. Dataset generation
#   2. Chirp extraction
# Is repeated before the model is trained,
# a new dataset is generated,
# and the model is tested on that
generations: 20
